# Generated by Django 4.2.17 on 2024-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='categoria',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Notificacion', 'Notificación'), ('Suscripcion', 'Suscripción'), ('Transaccion', 'Transacción'), ('Analisis', 'Análisis'), ('Sesion', 'Sesión'), ('Rol', 'Rol')], max_length=50),
        ),
    ]
