# Generated by Django 4.2.17 on 2024-12-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estado_categoria'),
        ('usuarios', '0003_rename_usuario_rol_alter_rol_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['-creado'], 'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.RemoveField(
            model_name='rol',
            name='activo',
        ),
        migrations.AddField(
            model_name='rol',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoria': 'Rol'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
    ]
