# Generated by Django 4.2.17 on 2024-12-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_tiponotificacion_usuario_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='tiponotificacion',
            options={'ordering': ['-severidad', 'nombre'], 'verbose_name': 'tipoNotificacion', 'verbose_name_plural': 'tipoNotificaciones'},
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
        migrations.AlterModelTable(
            name='tiponotificacion',
            table='tipoNotificacion',
        ),
    ]
