# Generated by Django 4.2.17 on 2024-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='tipo',
            new_name='tipo_notificacion',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='usuario_destino',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='activo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Último acceso'),
        ),
    ]
