# Generated by Django 4.2.17 on 2024-12-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_tipo_notificacion_tipo_notificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_acceso',
        ),
    ]
